name: "Keith Alpichi's Technical Blog & Portfolio"
description: "Want to learn to code? I'm a self-taught web developer sharing my experiences and publications of my work. I am currently looking for a full-time full-stack web developer position."
meta_description: "Keith Alpichi's Blog & Portfolio"
keywords: "software engineering, web development, code, programming"
url: "https://keithalpichi.github.io/"
logo: /assets/images/avatar-ka.png

markdown: kramdown

highlighter: rouge
gems:
  - rouge
  - jekyll-seo-tag
  - jekyll-sitemap

#paginate: 20
#paginate_path: "/page:num/"
baseurl: /
domain_name: 'https://keithalpichi.github.io'
google_analytics: 'UA-49683420-3'
disqus: true
disqus_shortname: 'keithalpichi'

# Details for the RSS feed generator
url: 'keithalpichi.github.io'
author: 'Keith Alpichi'

#Social URL links
twitter:
  usernme: keithalpichi
linkedin_url: https://linkedin.com/in/keithalpichi
twitter_url: https://twitter.com/keithalpichi
github_url: https://github.com/keithalpichi
stackoverflow_url: https://stackoverflow.com/users/5796559/keitha
instagram_url: https://www.instagram.com/keithalpichi/
quora_url: https://www.quora.com/profile/Keith-Alpichi


permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
