name: "Keith Alpichi"
author: 'Keith Alpichi'
description: "Software engineer, entrepreneur, and California Beach Bum"
meta_description: "Keith Alpichi's Blog & Portfolio"
keywords: "software engineer, web development, code, programming"
url: 'http://keithalpichi.com/' #"https://keithalpichi.github.io/"
logo: /assets/images/avatar-ka.png

markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge
plugins_dir:
  - rouge
  - jekyll-seo-tag
  - jekyll-sitemap

#paginate: 20
#paginate_path: "/page:num/"
domain_name: 'keithalpichi.com' #'https://keithalpichi.github.io'
google_analytics: 'UA-49683420-3'
disqus: true
disqus_shortname: 'keithalpichi'

#Social URL links
twitter:
  usernme: keithalpichi
linkedin_url: https://linkedin.com/in/keithalpichi
twitter_url: https://twitter.com/keithalpichi
github_url: https://github.com/keithalpichi
stackoverflow_url: https://stackoverflow.com/users/5796559/keitha
instagram_url: https://www.instagram.com/keithalpichi/
quora_url: https://www.quora.com/profile/Keith-Alpichi


permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
