name: "Keith Alpich's Technical Blog & Portfolio"
description: "Self-taught Python engineer sharing my experiences and work in Python, Flask and more!"
meta_description: "Keith Alpichi's Blog & Portfolio | Python & Flask"

markdown: Kramdown
highlighter: rouge
#gems: [jekyll-paginate]

#paginate: 20
#paginate_path: "/page:num/"
baseurl: /
domain_name: 'https://keithalpichi.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'keithalpichi'

# Details for the RSS feed generator
url:            'keithalpichi.github.io'
author:         'Keith Alpichi'

#Social URL links
authorTwitter:  'keithalpichi'
myLinkedin: 'https://linkedin.com/in/keithalpichi'
myGithub: 'https://github.com/keithalpichi'
myTwitter: 'https://twitter.com/keithalpichi'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
